spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/store
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml